### ISSUE TITLE
Potential prefix problem (Fowl)

### ISSUE THREAD

**Issue by tholiebig** [dwerft/dmo#2]
Version: 1.1

Seems to me that there is an extra prefix declaration:
`  xmlns:Fowl="http://www.digitalmediaontology.org/#http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23"`
That is used for two OWL vocabulary entities (`Fowl:equivalentProperty`, `Fowl:equivalentClass`) which should use the standard `owl` prefix.

**Comment by MarkGuelbahar** [comment]
Oops, that was a bug coming from the export out of webprotege. There's no Fowl any more, and never was intended to be anywhere in here...
Thanks for spotting! :)
